In [258]:
import pandas as pd
import numpy as np
import re
import nltk
nltk.download('stopwords')
nltk.download('punkt')
from nltk.corpus import names, stopwords, words
from nltk.corpus import stopwords
from nltk.tokenize import * 
from textblob import TextBlob

df = pd.read_csv('data job posts.csv')
df['jobpost'].tail()

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\siti.nadiyah\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\siti.nadiyah\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

18996    Technolinguistics NGO\r\n\r\n\r\nTITLE:  Senio...
18997    "Coca-Cola Hellenic Bottling Company Armenia" ...
18998    "Coca-Cola Hellenic Bottling Company Armenia" ...
18999    San Lazzaro   LLC\r\n\r\n\r\nTITLE:  Head of O...
19000    "Kamurj" UCO CJSC\r\n\r\n\r\nTITLE:  Lawyer in...
Name: jobpost, dtype: object

In [259]:
df['ApplicationDate'] = df['jobpost'].str.extract(re.compile(r"(\d\d [a-zA-Z]+ \d\d\d\d)"), expand=True)

In [260]:
df['ApplicationDate'].tail()

18996    29 December 2015
18997    30 December 2015
18998    30 December 2015
18999    30 December 2015
19000    30 December 2015
Name: ApplicationDate, dtype: object

In [261]:
df['Duration'] = df['jobpost'].str.extract(re.compile(r"(\d [a-zA-Z]+)"), expand=True)

In [262]:
df['Duration'].tail()

18996     5 years
18997    3 months
18998    3 months
18999      1 year
19000      1 year
Name: Duration, dtype: object

In [263]:
df['title'] = df['jobpost'].str.extract(re.compile(r"(?s)TITLE\s*:\s*(.*)(?:$)"))

In [264]:
df['title'].tail()

18996    Senior Creative UX/ UI Designer\r\n\r\n\r\nTER...
18997    Category Development Manager\r\n\r\n\r\nTERM: ...
18998    Operational Marketing Manager\r\n\r\n\r\nTERM:...
18999    Head of Online Sales Department\r\n\r\n\r\nDUR...
19000    Lawyer in Legal Department\r\n\r\n\r\nTERM:  F...
Name: title, dtype: object

In [265]:
df['Location'] = df['jobpost'].str.extract(re.compile(r"(?s)LOCATION:(.*)(?=\r)"))
df['Location'].tail()
df['Responsibility'] = df['jobpost'].str.extract(re.compile(r"(?s)JOB RESPONSIBILITIES:(.*)(?=\r)"))
df['Responsibility'].tail()

18996    \r\n- Work closely with product and business t...
18997    \r\n- Establish and manage Category Management...
18998      \r\n- Develop, establish and maintain market...
18999      \r\n- Handle the project activites of the on...
19000    \r\n- Properly provide internal legal services...
Name: Responsibility, dtype: object

In [266]:
#Identify the company with the most number of job ads in the past 2 years
df[df.Year >= 2014].groupby(['Company','Year']).size().reset_index().sort_values([0,'Year'], ascending = False)

                                                Company  Year   0
834           Mentor Graphics Development Services CJSC  2014  47
258                                       ArmenTel CJSC  2014  45
907                                 Orange Armenia CJSC  2014  45
392                                   Career Center NGO  2015  36
835           Mentor Graphics Development Services CJSC  2015  36
29    "Coca-Cola Hellenic Bottling Company Armenia" ...  2015  34
259                                       ArmenTel CJSC  2015  33
1244                               World Vision Armenia  2014  32
446                                  Converse Bank CJSC  2015  30
731                                       Joomag AM LLC  2015  30
932                                         PicsArt LLC  2015  30
354                                    BetArchitect LLC  2015  28
1158              Tumo Center for Creative Technologies  2015  28
28    "Coca-Cola Hellenic Bottling Company Armenia" ...  2014  28
963       Questrade International Inc., Armenian Branch  2014  27
353                                    BetArchitect LLC  2014  25
730                                       Joomag AM LLC  2014  25
964       Questrade International Inc., Armenian Branch  2015  24
1245                               World Vision Armenia  2015  24
908                                 Orange Armenia CJSC  2015  23
391                                   Career Center NGO  2014  23
525                       Energize Global Services CJSC  2015  22
645                              HSBC Bank Armenia CJSC  2015  21
1270                               Zeppelin Armenia LLC  2015  21
735                       K-Telecom CJSC (VivaCell-MTS)  2015  20
245                              Ardshininvestbank CJSC  2014  20
850                                        Monitis CJSC  2015  19
445                                  Converse Bank CJSC  2014  18
210                                     Ameriabank CJSC  2014  17
504                                  EPAM Systems, Inc.  2014  17
...                                                 ...   ...  ..
1138                      The World Bank Armenia Office  2014   1
1142                      The World Bank Yerevan office  2014   1
1144          Time to Print Salon of Operative Printing  2014   1
1151                                 Trans Alliance Ltd  2014   1
1155                          Tufenkian Hospitality LLC  2014   1
1163                                     UNICEF Armenia  2014   1
1164                              UNICEF Armenia Office  2014   1
1173  USAID Support to the Armenian National Assembl...  2014   1
1184  United Nations High Commissioner for Refugees ...  2014   1
1192        United Nations World Food Programme Armenia  2014   1
1196                                   VGM Partners Ltd  2014   1
1205                                 VTB Bank (Armenia)  2014   1
1209                                      VadaTech CJSC  2014   1
1210                                         Vagota LLC  2014   1
1213                                        Vallex Tour  2014   1
1216                                      Vas Group Ltd  2014   1
1220                               Veya Investments Ltd  2014   1
1222                                           Veya Ltd  2014   1
1225                                   VindexNumika LLC  2014   1
1226                                Vink Consulting LLC  2014   1
1228                                        WAELCON LLC  2014   1
1235                                      Westtrans LLC  2014   1
1240                          World Bank Yerevan Office  2014   1
1242  World Council of Churches Armenia Inter-Church...  2014   1
1246                               World Vision Georgia  2014   1
1251                                          Xsoft LLC  2014   1
1257                                   Yerevan TPP CJSC  2014   1
1262            Zangezur Copper Molybdenum Combine CJSC  2014   1
1273                                        e-Works LLC  2014   1
1276                                          iCity LLC  2014   1

[1278 rows x 3 columns]

In [267]:
#Identify the month with the largest number of job ads over the years
large_ads = df.groupby(['Month']).size()
large_ads.sort_values(ascending=False)

Month
3     1702
2     1665
6     1662
9     1652
10    1637
8     1613
7     1595
5     1580
11    1573
4     1466
12    1432
1     1424
dtype: int64

In [268]:
stopwds = stopwords.words('english')
def stop_words(string):
    if string is not None:  
        stop_words = set(stopwords.words('english'))
        word_tokens = word_tokenize(string) 
        string = [w for w in word_tokens if not w in stop_words] 
        string = [] 
        
        for w in word_tokens: 
            if w not in stop_words: 
                filtered_sentence.append(w) 
            else:
                string = ''
                return string

In [269]:
df['Responsibility'] = df['Responsibility'].apply(stop_words)

NameError: name 'filtered_sentence' is not defined